{{- if and .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-demo-mychart.name" . }}
    helm.sh/chart: {{ include "k8s-demo-mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "k8s-demo-mychart.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "k8s-demo-mychart.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-demo-mychart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
