{{- if gt .Values.replicaCount 1.0 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-demo-mychart.name" . }}
    helm.sh/chart: {{ include "k8s-demo-mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "k8s-demo-mychart.fullname" . }}
spec:
  selector:
    matchLabels:
      pp.kubernetes.io/name: {{ include "k8s-demo-mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.minAvailable }}
{{- end }}
