{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-demo-mychart.name" . }}
    helm.sh/chart: {{ include "k8s-demo-mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "k8s-demo-mychart.serviceAccountName" . }}
{{- end -}}
