{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-demo-blue-green.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-demo-blue-green.name" . }}
    helm.sh/chart: {{ include "k8s-demo-blue-green.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ required "A valid .Values.targetServiceName entry required!" $.Values.targetServiceName }}
              servicePort: {{ required "A valid .Values.targetServicePort entry required!" $.Values.targetServicePort }}
  {{- end }}
{{- end }}
